# frozen_string_literal: true

require 'fileutils'
require 'rbconfig'

module Echoes
  # Puts launcher wrappers into place so the user can easily launch echoes.
  # On macOS: copies thin Echoes.app / EchoesEmbed.app bundles to ~/Applications/.
  # On Windows: drops echoes.bat into the user's home/bin or specified directory.
  module Installer
    USER_APPS_DIR = File.expand_path('~/Applications')
    BUNDLES = %w[Echoes.app EchoesEmbed.app].freeze

    module_function

    def is_windows?
      RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
    end

    def install(source_root: default_source_root, target_dir: nil)
      if is_windows?
        target_dir ||= File.expand_path('~/bin')
        FileUtils.mkdir_p(target_dir)
        bat_path = File.join(target_dir, 'echoes.bat')
        real_launcher = File.join(source_root, 'exe', 'echoes')
        File.write(bat_path, <<~BAT)
          @echo off
          ruby "#{real_launcher}" %*
        BAT
        puts "Installed echoes.bat wrapper at #{bat_path}"
        puts "Please ensure #{target_dir} is in your system PATH to run `echoes` from any command prompt."
        [bat_path]
      else
        target_dir ||= USER_APPS_DIR
        FileUtils.mkdir_p(target_dir)

        installed = []
        BUNDLES.each do |bundle|
          source = File.join(source_root, bundle)
          unless Dir.exist?(source)
            warn "echoes install: #{bundle} not found at #{source} (skipping)"
            next
          end
          target = File.join(target_dir, bundle)
          write_wrapper(source, target)
          installed << target
        end

        if installed.empty?
          puts 'echoes install: nothing to do.'
        else
          puts 'Installed:'
          installed.each { |t| puts "  #{t}" }
          puts
          puts 'Re-run `echoes install` after `gem update echoes` to refresh the shortcuts.'
        end
        installed
      end
    end

    def uninstall(target_dir: nil)
      if is_windows?
        target_dir ||= File.expand_path('~/bin')
        bat_path = File.join(target_dir, 'echoes.bat')
        if File.exist?(bat_path)
          File.delete(bat_path)
          puts "Removed #{bat_path}"
          [bat_path]
        else
          puts "echoes uninstall: echoes.bat not found (nothing to remove)."
          []
        end
      else
        target_dir ||= USER_APPS_DIR
        removed = []
        BUNDLES.each do |bundle|
          target = File.join(target_dir, bundle)
          next unless Dir.exist?(target)
          FileUtils.remove_entry(target)
          removed << target
        end
        if removed.empty?
          puts 'echoes uninstall: nothing to remove.'
        else
          removed.each { |t| puts "Removed #{t}" }
        end
        removed
      end
    end

    def default_source_root
      File.expand_path('../..', __dir__)
    end

    def write_wrapper(source_bundle, target_bundle)
      bundle_name = File.basename(target_bundle)
      executable  = bundle_name.delete_suffix('.app')

      FileUtils.mkdir_p(File.join(target_bundle, 'Contents', 'MacOS'))

      source_plist = File.join(source_bundle, 'Contents', 'Info.plist')
      if File.exist?(source_plist)
        FileUtils.cp(source_plist, File.join(target_bundle, 'Contents', 'Info.plist'))
      end

      script_path = File.join(target_bundle, 'Contents', 'MacOS', executable)
      File.write(script_path, <<~SHELL)
        #!/bin/bash
        # Auto-generated by `echoes install`. Re-run after `gem update
        # echoes` so this points at the current installed location.
        exec "#{source_bundle}/Contents/MacOS/#{executable}"
      SHELL
      File.chmod(0o755, script_path)
    end
  end
end
