#!/usr/bin/env ruby
# frozen_string_literal: true

case ARGV.first
when 'install', 'uninstall'
  require 'echoes/installer'
  Echoes::Installer.public_send(ARGV.shift)
else
  require 'echoes/cli'
  Echoes::CLI.run(ARGV)
end
